import type { PixelSprite, SpriteSheet } from '../spriteTypes';

// 손님 스프라이트 생성기.
// 손님 16종을 전부 손으로 그리는 대신, 같은 치비 템플릿(큰 머리 + 작은 몸, 오른쪽 응시)에
// 머리/피부/옷 색과 소품 오버레이만 바꿔 만든다. 스타일이 통일되고 실수(행 길이)도 없다.

const K = '#111827'; // 외곽선

interface ChibiOpts {
  hair: string;
  skin: string;
  shirt: string;
  shirtHi: string;
  pants: string;
  eye?: string;
  // 추가 팔레트 (오버레이용)
  extra?: Record<string, string>;
  // 오버레이: '.' 은 그대로, 다른 문자는 덮어쓴다
  overlay?: string[];
  // 템플릿 자체 변형
  template?: string[];
}

const BASE: string[] = [
  '................',
  '.....kkkkkk.....',
  '....khhhhhhk....',
  '....khhhhhhk....',
  '....kffffffk....',
  '....kfeffefk....',
  '....kffffffk....',
  '.....kffffk.....',
  '....ksssssssk...',
  '...kssssssssk...',
  '...ksSssssSsk...',
  '...kssssssssk...',
  '....kppppppk....',
  '....kppkkppk....',
  '....kppk.kppk...',
  '....kkkk.kkkk...',
];

function chibi(o: ChibiOpts): PixelSprite {
  const rows = (o.template ?? BASE).map((r) => r.split(''));
  if (o.overlay) {
    o.overlay.forEach((r, y) => {
      for (let x = 0; x < 16; x++) {
        const ch = r[x];
        if (ch && ch !== '.') rows[y][x] = ch;
      }
    });
  }
  return {
    w: 16,
    h: 16,
    rows: rows.map((r) => r.join('')),
    palette: { k: K, h: o.hair, f: o.skin, e: o.eye ?? K, s: o.shirt, S: o.shirtHi, p: o.pants, w: '#ffffff', ...(o.extra ?? {}) },
  };
}

// 자주 쓰는 색
const SKIN = '#fcd9b6';
const SKIN_RED = '#f4a7a0';
const HAIR_BLACK = '#1f2937';
const HAIR_BROWN = '#7c4a24';

export const ENEMY_SPRITES: SpriteSheet = {
  // 담배 손님: 노란 후드, 입에 담배, 슬리퍼
  e_cig: chibi({
    hair: HAIR_BLACK,
    skin: SKIN,
    shirt: '#facc15',
    shirtHi: '#fde68a',
    pants: '#1f2937',
    extra: { r: '#ef4444', o: '#f59e0b' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..........kwwr..',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '....kook.kook...',
      '....kkkk.kkkk...',
    ],
  }),
  // 술 취한 손님: 빨간 얼굴, 풀린 넥타이, 소주병, 감은 눈
  e_drunk: chibi({
    hair: HAIR_BLACK,
    skin: SKIN_RED,
    shirt: '#e2e8f0',
    shirtHi: '#cbd5e1',
    pants: '#334155',
    extra: { r: '#dc2626', g: '#16a34a', G: '#4ade80', b: '#f472b6' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.....kkkkkk.....',
      '.....bffffb.....',
      '................',
      '.......r....kGk.',
      '.......r....kgk.',
      '.......r....kgk.',
      '............kkk.',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 가격 손님: 보라 카디건, 물건 들고 물음표
  e_price: chibi({
    hair: HAIR_BROWN,
    skin: SKIN,
    shirt: '#a78bfa',
    shirtHi: '#c4b5fd',
    pants: '#1e293b',
    extra: { y: '#fde047', q: '#ffffff' },
    overlay: [
      '............qqq.',
      '..............q.',
      '.............q..',
      '.............q..',
      '................',
      '.............q..',
      '................',
      '................',
      '............kkkk',
      '............kyyk',
      '............kyyk',
      '............kkkk',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 라면 손님: 주황 티, 컵라면, 김
  e_ramen: chibi({
    hair: HAIR_BLACK,
    skin: SKIN,
    shirt: '#f97316',
    shirtHi: '#fdba74',
    pants: '#1e3a8a',
    extra: { r: '#dc2626', c: '#94a3b8' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '.............w..',
      '..............w.',
      '.............w..',
      '................',
      '............krrk',
      '............kwwk',
      '............kwwk',
      '.............kk.',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 배달기사: 초록 헬멧, 검은 자켓, 형광 조끼, 배달 가방
  e_delivery: chibi({
    hair: '#22c55e',
    skin: SKIN,
    shirt: '#1f2937',
    shirtHi: '#a3e635',
    pants: '#111827',
    extra: { g: '#22c55e', G: '#86efac', b: '#5b3a1e', B: '#7c4a24' },
    overlay: [
      '................',
      '.....kkkkkk.....',
      '....kgGGGGgk....',
      '....kggggggk....',
      '...kkggggggkk...',
      '................',
      '................',
      '................',
      '............kkkk',
      '............kBbk',
      '............kbbk',
      '............kbbk',
      '............kkkk',
      '................',
      '................',
      '................',
    ],
  }),
  // 단체 손님: 파티 모자, 빨간 티, 손 들고 환호
  e_party: chibi({
    hair: HAIR_BLACK,
    skin: SKIN,
    shirt: '#ef4444',
    shirtHi: '#fca5a5',
    pants: '#1e293b',
    extra: { r: '#f43f5e', y: '#fde047' },
    overlay: [
      '.......y........',
      '......krk.......',
      '.....kryrk......',
      '................',
      '................',
      '..............kk',
      '.............kfk',
      '.............kfk',
      '............kfk.',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 술 취한 친구들: 자주 옷, 붉은 얼굴, 맥주캔, 팔 벌림
  e_drunkSquad: chibi({
    hair: HAIR_BROWN,
    skin: SKIN_RED,
    shirt: '#d946ef',
    shirtHi: '#f0abfc',
    pants: '#312e81',
    extra: { c: '#cbd5e1', r: '#ef4444', b: '#f472b6' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.....bffffb.....',
      '................',
      '............kck.',
      '.kkk........krk.',
      'kfffk.......kck.',
      '.kkk........kkk.',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 봉투 손님: 연두 옷, 큰 흰 봉투
  e_bag: chibi({
    hair: HAIR_BLACK,
    skin: SKIN,
    shirt: '#84cc16',
    shirtHi: '#bef264',
    pants: '#3f3f46',
    extra: { g: '#d1d5db' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '............kk..',
      '...........k..k.',
      '...........kwwk.',
      '..........kwwwwk',
      '..........kwgwwk',
      '..........kwwwwk',
      '..........kwwwwk',
      '..........kkkkkk',
      '................',
      '................',
    ],
  }),
  // 새벽 3시 진상: 빨간 옷, 화난 눈썹, 벌린 입, 분노 표시
  e_karen: chibi({
    hair: '#7c2d12',
    skin: '#f5b5a3',
    shirt: '#dc2626',
    shirtHi: '#f87171',
    pants: '#1f2937',
    extra: { r: '#ef4444', a: '#fecaca' },
    overlay: [
      '.............r.r',
      '..............r.',
      '.............r.r',
      '................',
      '.....k....k.....',
      '......k..k......',
      '................',
      '.....kkkk.......',
      '......kk........',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 충전기 손님: 하늘색 옷, 스마트폰, 케이블
  e_charger: chibi({
    hair: HAIR_BLACK,
    skin: SKIN,
    shirt: '#22d3ee',
    shirtHi: '#a5f3fc',
    pants: '#1e293b',
    extra: { b: '#3b82f6', r: '#ef4444', c: '#e2e8f0' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '............kkkk',
      '............kbbk',
      '............kbrk',
      '............kkkk',
      '.............c..',
      '.............c..',
      '............c...',
      '................',
    ],
  }),
  // 택배 손님: 얼굴까지 쌓인 박스, 머리만 삐죽
  e_parcel: chibi({
    hair: HAIR_BLACK,
    skin: SKIN,
    shirt: '#a16207',
    shirtHi: '#ca8a04',
    pants: '#3f3f46',
    extra: { b: '#b45309', B: '#d97706', t: '#fde68a' },
    overlay: [
      '................',
      '................',
      '................',
      '...kkkkkkkkk....',
      '...kBBBtBBBk....',
      '...kbbbtbbbk....',
      '...kbbbtbbbk....',
      '...kkkkkkkkk....',
      '..kBBBBtBBBBk...',
      '..kbbbbtbbbbk...',
      '..kbbbbtbbbbk...',
      '..kkkkkkkkkkk...',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 화장실 손님: 노란 옷, 땀방울, 다리 꼬임
  e_toilet: chibi({
    hair: HAIR_BROWN,
    skin: SKIN,
    shirt: '#fde047',
    shirtHi: '#fef08a',
    pants: '#0f172a',
    extra: { b: '#67e8f9' },
    overlay: [
      '................',
      '................',
      '............b...',
      '...........bb...',
      '............b...',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.....kppppk.....',
      '.....kpkkpk.....',
      '......kppk......',
      '......kkkk......',
    ],
  }),
  // 사장님 불러 손님: 자주 정장, 선글라스, 확성기
  e_caller: chibi({
    hair: HAIR_BLACK,
    skin: SKIN,
    shirt: '#be185d',
    shirtHi: '#f472b6',
    pants: '#1f2937',
    extra: { y: '#fde047', g: '#94a3b8' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '....kkkkkkkk....',
      '................',
      '............kk..',
      '...........kyyk.',
      '..........kyyyyk',
      '...........kyyk.',
      '............kk..',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 유령 손님: 커스텀 (떠 있는 반투명 몸)
  e_ghost: {
    w: 16,
    h: 16,
    palette: { k: '#312e81', w: '#eef2ff', l: '#c7d2fe', e: '#111827', m: '#818cf8' },
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kwwwwwwk....',
      '...kwwwwwwwwk...',
      '...kwwewwewwk...',
      '...kwwwwwwwwk...',
      '...kwwwmmwwwk...',
      '...kwwwwwwwwk...',
      '...kwwwwwwwwk...',
      '...klwwwwwwlk...',
      '...kllwwwwllk...',
      '...kllllllllk...',
      '...kl.kll.klk...',
      '...kk.kkk.kkk...',
      '................',
      '................',
    ],
  },
  // 좀비 손님: 초록 피부, 찢어진 회색 옷, 팔 앞으로, 컵라면
  e_zombie: chibi({
    hair: '#365314',
    skin: '#86efac',
    shirt: '#6b7280',
    shirtHi: '#4b5563',
    pants: '#374151',
    extra: { r: '#ef4444', c: '#dc2626' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.........r......',
      '................',
      '................',
      '............kkkk',
      '...kffffffffffk.',
      '...kkkkkkkkkkkk.',
      '..............cw',
      '..............ww',
      '................',
      '................',
      '................',
    ],
  }),
  // 도시락 조각: 작은 밥 덩어리에 눈
  e_lunchPiece: {
    w: 10,
    h: 10,
    palette: { k: '#111827', w: '#f8fafc', g: '#84cc16', r: '#dc2626', e: '#111827' },
    rows: [
      '...kkkk...',
      '..kwwwwk..',
      '.kwewwewk.',
      '.kwwwwwwk.',
      'kwwwrrwwwk',
      'kgwwwwwwgk',
      'kggwwwwggk',
      '.kgggggk..',
      '..kkkkk...',
      '..........',
    ],
  },
  // ───── 보스 ─────
  // 폐기 직전 도시락: 검은 용기, 반찬, 사악한 눈, 악취 연기
  boss_lunchbox: {
    w: 16,
    h: 16,
    palette: { k: '#111827', b: '#1f2937', B: '#374151', w: '#f8fafc', r: '#dc2626', g: '#84cc16', G: '#4ade80', y: '#fde047', e: '#ef4444', s: '#a3e635' },
    rows: [
      '..s.....s...s...',
      '.s.s...s...s.s..',
      '..s.....s...s...',
      '.kkkkkkkkkkkkkk.',
      'kBBBBBBBBBBBBBBk',
      'kBkkkkkkkkkkkkBk',
      'kBkwwwwkrrkyykBk',
      'kBkwewwkrrkyykBk',
      'kBkwwwwkkkkkkkBk',
      'kBkwwwwkGGGGGkBk',
      'kBkkkkkkGeGGGkBk',
      'kBkyyyykGGGGGkBk',
      'kBkyyyykkkkkkkBk',
      'kBkkkkkkkkkkkkBk',
      'kbbbbbbbbbbbbbbk',
      '.kkkkkkkkkkkkkk.',
    ],
  },
  // 새벽 3시 단체 손님: 머리 3개가 겹친 덩어리, 파티 모자, 맥주캔
  boss_party: {
    w: 16,
    h: 16,
    palette: { k: '#111827', h: '#1f2937', f: '#fcd9b6', e: '#111827', r: '#ef4444', R: '#fca5a5', y: '#fde047', c: '#cbd5e1', b: '#7c4a24' },
    rows: [
      '.......y........',
      '..kk..krk..kk...',
      '.khhk.kkk.khhk..',
      'khhhhkhhhkhhhhk.',
      'kffffkhhhkffffk.',
      'kfeffkffffkfeffk',
      'kffffkfeffkffffk',
      '.kffkkffffkkffk.',
      '.krrrkkffkkrrrk.',
      'krrrrrkkkkrrrrrk',
      'krRrrrrrrrrrrRrk',
      'krrrrrrrrrrrrrrk',
      '.kkkkkkkkkkkkkk.',
      '.kbbk.kbbk.kbbk.',
      '.kbbk.kbbk.kbbk.',
      '.kkkk.kkkk.kkkk.',
    ],
  },
  // 본사 직원: 남색 정장, 안경, 사원증, 클립보드
  boss_inspector: chibi({
    hair: '#0f172a',
    skin: SKIN,
    shirt: '#1e3a8a',
    shirtHi: '#3b82f6',
    pants: '#0f172a',
    extra: { g: '#bfdbfe', c: '#e2e8f0', b: '#2563eb', y: '#fde047' },
    overlay: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '....kgeggegk....',
      '................',
      '................',
      '.......w....kkkk',
      '.......b....kcck',
      '.......y....kcck',
      '............kkkk',
      '................',
      '................',
      '................',
      '................',
    ],
  }),
  // 월말 매출 마감: 보라 소용돌이 + 빨간 숫자 + 빨간 눈
  boss_closing: {
    w: 16,
    h: 16,
    palette: { k: '#1e1b4b', p: '#7e22ce', P: '#a855f7', d: '#3b0764', r: '#ef4444', e: '#f87171', w: '#f1f5f9', y: '#fde047' },
    rows: [
      '.....kkkkkk.....',
      '...kkpppppdkk...',
      '..kpPPpdddppdk..',
      '.kpPddpppdddpdk.',
      '.kPdrkkdppdrppk.',
      'kpdrekdpddrekpdk',
      'kpdrrkdpddrrkpdk',
      'kpddppddpppdppdk',
      'kpdwwwdwwwdwwpdk',
      'kppdwddwdwdwddpk',
      '.kpdwwwdwwdwwpk.',
      '.kppdppddpppppk.',
      '..kpPpdyyydppk..',
      '...kkpppppppkk..',
      '....kk.kk.kk....',
      '................',
    ],
  },
};
