import type { SpriteSheet } from '../spriteTypes';

// units3: 덱 슬롯 보강용 유닛 6종.
// base.ts 와 같은 규칙: 16x16, 1px 어두운 외곽선('k'), 캐릭터는 오른쪽을 봄, 투명 배경('.').
export const UNITS3_SPRITES: SpriteSheet = {
  // 핫바 기계: 회전 그릴 위에 핫바 두 줄, 아래는 유리창
  hotbar: {
    w: 16,
    h: 16,
    palette: { k: '#111827', m: '#6b7280', g: '#9ca3af', r: '#ea580c', b: '#c2410c', y: '#fbbf24', w: '#e5e7eb', d: '#374151' },
    rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '..kmmmmmmmmmmk..',
      '..kmggggggggmk..',
      '..kmgrrbrrbrgmk.',
      '..kmgyyyyyyygmk.',
      '..kmgrrbrrbrgmk.',
      '..kmgyyyyyyygmk.',
      '..kmggggggggmk..',
      '..kmmmmmmmmmmk..',
      '..kmwwwwwwwwmk..',
      '..kmwddddddwmk..',
      '..kmwwwwwwwwmk..',
      '..kmmmmmmmmmmk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },

  // 바코드 스캐너: 손잡이형, 앞쪽에서 붉은 레이저가 나간다
  scanner: {
    w: 16,
    h: 16,
    palette: { k: '#111827', d: '#1f2937', g: '#4b5563', r: '#ef4444', p: '#f87171', w: '#e5e7eb', b: '#111827' },
    rows: [
      '................',
      '................',
      '....kkkkkk......',
      '...kddddddk.....',
      '...kdwwwwdk.....',
      '...kdwbbwdkrrr..',
      '...kdwwwwdkrpr..',
      '...kddddddkrrr..',
      '...kggggggk.....',
      '....kggggk......',
      '....kdggdk......',
      '....kdggdk......',
      '....kddddk......',
      '...kkddddkk.....',
      '...kdddddddk....',
      '....kkkkkkk.....',
    ],
  },

  // 즉석 떡볶이: 붉은 국물이 든 넓은 팬, 김이 오른다
  tteok: {
    w: 16,
    h: 16,
    palette: { k: '#111827', m: '#9ca3af', s: '#6b7280', r: '#dc2626', o: '#f97316', w: '#fecaca', y: '#fde047' },
    rows: [
      '.....w....w.....',
      '....w....w..w...',
      '.....w..w....w..',
      '................',
      '..kkkkkkkkkkkk..',
      '..kmmmmmmmmmmk..',
      '..krrororrorrk..',
      '..krorrrorrrok..',
      '..krrorrrrorrk..',
      '..kroryrrorrok..',
      '..krrorrrrorrk..',
      '..kmmmmmmmmmmk..',
      '..ksssssssssskk.',
      '...ksssssssssk..',
      '....kkkkkkkkk...',
      '................',
    ],
  },

  // 슬러시 기계: 두 개의 투명 통에 빨강/파랑 슬러시, 위에 회전 뚜껑
  slush: {
    w: 16,
    h: 16,
    palette: { k: '#111827', m: '#9ca3af', g: '#d1d5db', b: '#06b6d4', c: '#67e8f9', r: '#ef4444', p: '#fca5a5', d: '#4b5563' },
    rows: [
      '................',
      '..kkkkk..kkkkk..',
      '..kmmmk..kmmmk..',
      '.kkgggkkkkgggkk.',
      '.kgcccgkkgpppgk.',
      '.kgbbbgkkgrrrgk.',
      '.kgcbcgkkgprpgk.',
      '.kgbbbgkkgrrrgk.',
      '.kgbcbgkkgrprgk.',
      '.kgbbbgkkgrrrgk.',
      '.kkgggkkkkgggkk.',
      '..kmmmk..kmmmk..',
      '..kdddkkkkdddk..',
      '.kkmmmmmmmmmmkk.',
      '.kmmmmmmmmmmmmk.',
      '..kkkkkkkkkkkk..',
    ],
  },

  // 사장님: 넉넉한 배, 금목걸이, 팔짱. 점장보다 나이 든 인상
  owner: {
    w: 16,
    h: 16,
    palette: { k: '#111827', h: '#4b5563', f: '#fcd9b6', e: '#111827', s: '#1e40af', w: '#e5e7eb', y: '#f59e0b', p: '#374151', b: '#92400e' },
    rows: [
      '................',
      '.....kkkkkk.....',
      '....khhhhhhk....',
      '....kfhhhhfk....',
      '....kffffffk....',
      '....kfeffeek....',
      '....kffffffk....',
      '.....kfbbfk.....',
      '....kkwwwwkk....',
      '...ksswyywssk...',
      '...kswwyywwsk...',
      '...ksswwwwssk...',
      '...kssswwsssk...',
      '....kppppppk....',
      '....kpp..ppk....',
      '....kkk..kkk....',
    ],
  },

  // 새벽 청소 여사님: 머릿수건, 앞치마, 대걸레를 들고 있다
  dawnCleaner: {
    w: 16,
    h: 16,
    palette: { k: '#111827', h: '#0ea5e9', f: '#fcd9b6', e: '#111827', a: '#e5e7eb', c: '#7dd3fc', p: '#334155', m: '#a16207', g: '#94a3b8' },
    rows: [
      '.............g..',
      '....kkkkkk..ggg.',
      '...khhhhhhk.ggg.',
      '...khhhhhhk..m..',
      '...kfffffk...m..',
      '...kfeffek...m..',
      '...kffffk....m..',
      '....kffk.....m..',
      '...kaaaakk...m..',
      '..kcaaaaak...m..',
      '..kaaaaaak...m..',
      '..kaccccak...m..',
      '..kaaaaaak..kk..',
      '...kppppk.......',
      '...kpp.pk.......',
      '...kk...kk......',
    ],
  },
};

// 조합 레시피 결과 유닛 4종. 재료의 특징을 한눈에 섞어 보이게 그린다.
export const RECIPE_SPRITES: SpriteSheet = {
  // 야식 세트: 쟁반 위에 삼각김밥 + 컵라면 + 핫바
  nightSnackSet: {
    w: 16,
    h: 16,
    palette: { k: '#111827', t: '#78350f', b: '#a16207', w: '#f8fafc', n: '#1f2937', r: '#ef4444', o: '#f97316', y: '#fbbf24', c: '#fed7aa' },
    rows: [
      '................',
      '....w.....rr....',
      '...www...krrk...',
      '..kwwwk..krrk...',
      '..kwnwk..kcck...',
      '..kwwwk..kcck...',
      '..kkkkk..kkkk...',
      '............oo..',
      '...........koyk.',
      '...........koyk.',
      '...........koyk.',
      '...........kook.',
      '..kkkkkkkkkkkk..',
      '..kbbbbbbbbbbk..',
      '..ktttttttttttk.',
      '...kkkkkkkkkkk..',
    ],
  },

  // 에너지 드링크 진열대: 형광 초록 캔이 줄지어 서 있고 위에 번개
  energyDrink: {
    w: 16,
    h: 16,
    palette: { k: '#111827', m: '#6b7280', g: '#84cc16', l: '#bef264', y: '#fde047', d: '#365314' },
    rows: [
      '.......yy.......',
      '......yy........',
      '.....yyyy.......',
      '.......yy.......',
      '..kkkkkkkkkkkk..',
      '..kmmmmmmmmmmk..',
      '..kglglglglglk..',
      '..kglglglglglk..',
      '..kgdgdgdgdgdk..',
      '..kmmmmmmmmmmk..',
      '..kglglglglglk..',
      '..kglglglglglk..',
      '..kgdgdgdgdgdk..',
      '..kmmmmmmmmmmk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },

  // 무인 계산대: 키오스크 화면 + 바코드 리더, 사람이 없다
  selfCheckout: {
    w: 16,
    h: 16,
    palette: { k: '#111827', m: '#475569', g: '#94a3b8', s: '#22d3ee', w: '#e0f2fe', d: '#0e7490', r: '#ef4444' },
    rows: [
      '...kkkkkkkkkk...',
      '...kmmmmmmmmk...',
      '...kmssssssmk...',
      '...kmswwwwsmk...',
      '...kmswddwsmk...',
      '...kmswwwwsmk...',
      '...kmssssssmk...',
      '...kmmmmmmmmk...',
      '...kmggggggmk...',
      '...kmgrrrrgmk...',
      '...kmggggggmk...',
      '...kmmmmmmmmk...',
      '..kkmmmmmmmmkk..',
      '..kmmmmmmmmmmk..',
      '..kmmmmmmmmmmk..',
      '..kkkkkkkkkkkk..',
    ],
  },

  // 빙결 구역: 바닥이 얼고 고드름이 솟아 있다
  freezeZone: {
    w: 16,
    h: 16,
    palette: { k: '#111827', i: '#38bdf8', l: '#bae6fd', w: '#e0f2fe', d: '#0369a1' },
    rows: [
      '..l..........l..',
      '..i....l.....i..',
      '..i....i.....i..',
      '.kik..kik...kik.',
      '.kik..kik...kik.',
      '.kkk..kkk...kkk.',
      '................',
      '....l.....l.....',
      '...kik...kik....',
      '...kkk...kkk....',
      '................',
      '.kkkkkkkkkkkkkk.',
      '.kiwliwliwliwik.',
      '.kdiididiididk..',
      '.kiwliwliwliwik.',
      '.kkkkkkkkkkkkkk.',
    ],
  },
};
