import type { SpriteSheet } from '../spriteTypes';

// units2 배치: 전자레인지 / 로또 / 택배 / 점장 / 고양이 / 10년차 알바 + 투사체.
// 캐릭터는 16x16 치비(큰 머리, 작은 몸), 오른쪽을 바라봄. 사물은 16x16 정면 뷰.
export const UNITS2_SPRITES: SpriteSheet = {
  // 전자레인지: 은색 박스, 검은 창 안에 노란 빛, 오른쪽 다이얼 2개 + 빨간 버튼
  microwave: {
    w: 16,
    h: 16,
    palette: {
      k: '#111827',
      w: '#f9fafb',
      s: '#d1d5db',
      d: '#9ca3af',
      b: '#1f2937',
      y: '#fde68a',
      o: '#f59e0b',
      g: '#4b5563',
      r: '#ef4444',
    },
    rows: [
      '.kkkkkkkkkkkkkk.',
      'kwwwwwwwwwwwwwwk',
      'kskkkkkkkkksssdk',
      'kskbbbbbbbksssdk',
      'kskbyyyyybksgsdk',
      'kskbyoooybkgwgdk',
      'kskbyoooybksgsdk',
      'kskbyoooybksssdk',
      'kskbyyyyybksgsdk',
      'kskbbbbbbbkgwgdk',
      'kskkkkkkkkksgsdk',
      'ksssssssssssssdk',
      'ksssssssssssrsdk',
      'kddddddddddddddk',
      '.kkkkkkkkkkkkkk.',
      '..kk........kk..',
    ],
  },
  // 로또 기계: 파란 몸체 + 노란 캡/띠, 검은 화면에 색색 로또 공, 금색 배출구
  lotto: {
    w: 16,
    h: 16,
    palette: {
      k: '#111827',
      b: '#2563eb',
      l: '#60a5fa',
      n: '#1e3a8a',
      y: '#facc15',
      g: '#d97706',
      d: '#0f172a',
      r: '#ef4444',
      e: '#22c55e',
      o: '#f97316',
      w: '#f9fafb',
    },
    rows: [
      '...kkkkkkkkkk...',
      '..kyyyyyyyyyyk..',
      '.klbkkkkkkkkbnk.',
      'klbkddddddddkbnk',
      'klbkrrdyydeekbnk',
      'klbkrrdyydeekbnk',
      'klbkddoodwwdkbnk',
      'klbkddoodwwdkbnk',
      'klbkkkkkkkkkkbnk',
      'kyyyyyyyyyyyyyyk',
      'klbbbbbbbbbbbbnk',
      'klbggggggggggbnk',
      'klbgkkkkkkkkgbnk',
      'klbggggggggggbnk',
      'knnnnnnnnnnnnnnk',
      'kkkkkkkkkkkkkkkk',
    ],
  },
  // 택배 접수기: 갈색 상자 3개(위 1, 아래 2), 위 상자에 흰 송장, 초록 스캐너
  parcel: {
    w: 16,
    h: 16,
    palette: {
      k: '#111827',
      h: '#d9a066',
      b: '#c47f3a',
      d: '#8f5a2b',
      t: '#f5deb3',
      w: '#ffffff',
      g: '#9ca3af',
      e: '#22c55e',
      n: '#166534',
      r: '#ef4444',
    },
    rows: [
      '.kkkkkkk........',
      'khhhhhhhk.......',
      'kbbbbbbbk.kkkkk.',
      'kbwwwwwbk.keeerk',
      'kbwgggwbk.kennek',
      'kbwwwwwbk.keeeek',
      'kbwgggwbk..keek.',
      'kbwwwwwbk..keek.',
      'kdddddddk..kkkk.',
      'kkkkkkkkkkkkkkkk',
      'khhhhhhkkhhhhhhk',
      'kbbbbbbkkbbbbbbk',
      'kbbttbbkkbbttbbk',
      'kbbttbbkkbbttbbk',
      'kddddddkkddddddk',
      'kkkkkkkkkkkkkkkk',
    ],
  },
  // 점장 (전설): 벗겨진 머리 + 흰 새치, 안경, 찌푸린 눈썹, 짙은 남색 조끼 + 흰 셔츠, 팔짱, 금색 명찰
  manager: {
    w: 16,
    h: 16,
    palette: {
      k: '#111827',
      h: '#6b7280',
      g: '#9ca3af',
      f: '#fcd9b6',
      e: '#111827',
      l: '#93c5fd',
      s: '#1f2937',
      m: '#9a3412',
      v: '#3730a3',
      u: '#312e81',
      w: '#f9fafb',
      y: '#fbbf24',
      p: '#374151',
    },
    rows: [
      '................',
      '.....kkkkkk.....',
      '....khhghhgk....',
      '....khhhfffk....',
      '....kfsffsfk....',
      '....kleslefk....',
      '....kllfllfk....',
      '.....kffmmk.....',
      '...kwvvwwvvwk...',
      '...kwvyyvvvwk...',
      '...kwwfwwfwwk...',
      '...kvvvvvvvvk...',
      '...kuuuuuuuuk...',
      '....kppkkppk....',
      '....kppk.kppk...',
      '....kkkk.kkkk...',
    ],
  },
  // 편의점 고양이: 치즈 줄무늬, 앉은 자세, 큰 초록 눈, 왼쪽에 꼬리 세움
  cat: {
    w: 16,
    h: 16,
    palette: {
      k: '#111827',
      o: '#f97316',
      d: '#c2410c',
      p: '#fda4af',
      w: '#fff7ed',
      e: '#22c55e',
      n: '#f472b6',
    },
    rows: [
      '................',
      '.....kk....kk...',
      '.....kpk..kpk...',
      '....koodoodook..',
      'kkk.kooooooook..',
      'kok.kooeeoeeok..',
      'kdk.kooekoekok..',
      'kok.koowwwnwok..',
      'kok..kowwwwwk...',
      'kdk.kooooowwwk..',
      'kok.kodoodowwk..',
      'kok.koooooowwk..',
      'kokkkodoodowwk..',
      'kooooooooowwwk..',
      '.kkkkooooookwwk.',
      '.....kkkkkkkkkk.',
    ],
  },
  // 10년차 알바: 헝클어진 머리, 다크서클, 무표정, 초록 조끼, 오른손에 커피컵
  veteran: {
    w: 16,
    h: 16,
    palette: {
      k: '#111827',
      h: '#1f2937',
      f: '#fcd9b6',
      e: '#111827',
      c: '#a08cb0',
      m: '#9a3412',
      t: '#16a34a',
      a: '#15803d',
      w: '#f9fafb',
      b: '#78350f',
      p: '#374151',
    },
    rows: [
      '.....k..k.k.....',
      '....khkkhkhk....',
      '...khhhhhhhhk...',
      '....khhhhhhk....',
      '....khffhffk....',
      '....kfeffefk....',
      '....kfcffcfk....',
      '.....kffmmk.....',
      '...ktttwwtttk...',
      '...kttttttttkkkk',
      '...kttttttttfbbk',
      '...kttttttttfwwk',
      '...kaaaaaaaakwwk',
      '....kppkkppk.kk.',
      '....kppk.kppk...',
      '....kkkk.kkkk...',
    ],
  },
  // 투사체: 작은 삼각김밥
  p_onigiri: {
    w: 6,
    h: 6,
    palette: { k: '#1f2937', w: '#ffffff', b: '#111827' },
    rows: ['..kk..', '.kwwk.', 'kwwwwk', 'kwbbwk', 'kwbbwk', 'kkkkkk'],
    anchorX: 0.5,
    anchorY: 0.5,
  },
  // 투사체: 바코드 스캔 빛 (빨간 바탕 + 흰 세로선)
  p_barcode: {
    w: 8,
    h: 6,
    palette: { r: '#ef4444', w: '#ffffff', l: '#fca5a5' },
    rows: ['.llllll.', 'rwrwrrwr', 'rwrwrrwr', 'rwrwrrwr', 'rwrwrrwr', '.llllll.'],
    anchorX: 0.5,
    anchorY: 0.5,
  },
  // 투사체: 주황 라면 봉지 (빨간 띠 + 노란 면)
  p_ramen: {
    w: 7,
    h: 7,
    palette: { k: '#111827', o: '#f97316', r: '#dc2626', y: '#fde047' },
    rows: ['kkkkkkk', 'koooook', 'korrrok', 'koyyyok', 'koyoyok', 'koooook', 'kkkkkkk'],
    anchorX: 0.5,
    anchorY: 0.5,
  },
  // 투사체: 흰 영수증 (회색 글자 줄)
  p_receipt: {
    w: 6,
    h: 8,
    palette: { k: '#374151', w: '#ffffff', g: '#9ca3af' },
    rows: ['kkkkkk', 'kgggwk', 'kwwwwk', 'kggwwk', 'kwwwwk', 'kgggwk', 'kwwwwk', 'k.kk.k'],
    anchorX: 0.5,
    anchorY: 0.5,
  },
  // 투사체: 갈색 커피 방울 (하이라이트 + 그림자)
  p_coffee: {
    w: 7,
    h: 7,
    palette: { k: '#111827', b: '#92400e', d: '#451a03', w: '#fef3c7' },
    rows: ['...k...', '..kbk..', '.kwbbk.', 'kwbbbdk', 'kbbbddk', '.kbddk.', '..kkk..'],
    anchorX: 0.5,
    anchorY: 0.5,
  },
  // 투사체: 하늘색 얼음 결정
  p_ice: {
    w: 7,
    h: 7,
    palette: { c: '#38bdf8', w: '#e0f2fe', d: '#0284c7' },
    rows: ['...d...', '.d.c.d.', '..cwc..', 'dcwwwcd', '..cwc..', '.d.c.d.', '...d...'],
    anchorX: 0.5,
    anchorY: 0.5,
  },
  // 투사체: 금색 로또 공/동전 (가운데 숫자 획)
  p_lotto: {
    w: 7,
    h: 7,
    palette: { k: '#111827', y: '#facc15', g: '#a16207', w: '#fef9c3' },
    rows: ['..kkk..', '.kwyyk.', 'kwygyyk', 'kyygyyk', 'kyygyyk', '.kyyyk.', '..kkk..'],
    anchorX: 0.5,
    anchorY: 0.5,
  },
  // 투사체: 흰 택배 송장 (바코드 + 글자 줄)
  p_label: {
    w: 8,
    h: 6,
    palette: { k: '#111827', w: '#ffffff', g: '#9ca3af' },
    rows: ['kkkkkkkk', 'kggwwwwk', 'kwkwkkwk', 'kwkwkkwk', 'kwwwwggk', 'kkkkkkkk'],
    anchorX: 0.5,
    anchorY: 0.5,
  },
};
